#define _USE_MATH_DEFINES
#include <iostream>
#include <sstream>
#include <fstream>
#include <list>
#include <stdlib.h>
#include <math.h>
#include <algorithm>
#include <vector>
#include <string>
#include <time.h>
#include "../Chukyo/common2.h"
//#include <opencv2/opencv.hpp>
#include <omp.h>